
theme: jekyll-theme-cayman
logo: image: (Lava_Lamp__2817.gif)
title: Welcome to Mackenzie's Data Science Portfolio
description: The purpose of this website is to test my skills and show off what I know!
